---

- name: Enable gluster repo
  command: subscription-manager repos --enable="{{ item }}"
  with_items: "{{ gluster_repos }}"

- name: Install gluster deps
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ gluster_packages }}"

- name: Disable gluster repo
  command: subscription-manager repos --disable="{{ item }}"
  with_items: "{{ gluster_repos }}"