---
- include_tasks: aws.yml
  when: ansible_bios_version | search("amazon")
  
- name: Disable all repositories
  command: subscription-manager repos --disable="*"

# repeatable taks 
#- name: Disable yum-config-manager
#  command: yum-config-manager --disable \*

- name: Enable required repositories
  command: subscription-manager repos --enable="{{ item }}"
  with_items: "{{ repos_to_enable }}"

- name: Ensure subscription-manager updated
  yum:
    name: subscription-manager
    state: latest

