---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: ocp-configure-node
    box: rhel74_sub
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: vagrant
verifier:
  name: testinfra
  lint:
    name: flake8
