---
dependencies: []

galaxy_info:
  author: Mangirdas Judeikis
  description: Setup SSH for bastion host
  company: "Containers Ninja"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.2
  platforms:
    - name: EL
      versions:
      - 6
      - 7
  galaxy_tags:
    - cloud
    - system
    - development
