---

- name: Configure invetory groups  
  hosts: all
  roles:
    - ssh

- name: Prepare controller
  hosts: controller
  tasks:
  # TODO: we dont have defualt repo for ansible yet. its need to be enabled here for this. I should be called as separate role with variable
  roles:
  - prepare-controller