---
- name: Configure invetory groups
  hosts: all
  
- hosts: all
  roles:
   - subscription
   - ocp-pre-hooks

- hosts: all:!bastion
  roles:
   - docker

- hosts: masters
  roles:
   - ocp-pre-hooks-masters
