---
# This playbooks configured existing openshift cluster to use internal EFK
# Pre-reqs:
#  Some kind of block storage class is available

- name: Configure invetory groups
  hosts: all:!controller:!bastion
  tasks:
    - set_fact:
        openshift_logging_install_logging: "{{ amos_openshift_logging_install_logging }}"
        openshift_logging_install_eventrouter: "{{ amos_openshift_logging_install_eventrouter }}"

- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/init/main.yml
                                                                                             